# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.9
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      - id: isort
        args: ['--multi-line=3', '--trailing-comma', '--force-grid-wrap=0', '--use-parentheses']
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: ['-l 100']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-json
      - id: check-yaml
        args: ['--unsafe']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
        types: [python]
